cluster.name: ${CLUSTER_NAME}

node:
  name: ${NODE_NAME}
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}

discovery.zen:
  minimum_master_nodes: ${MINIMUM_MASTER_NODES}
  ping.unicast.hosts: ${HOSTS}

network:
  host: ${NETWORK_HOST}
  publish_host: ${NETWORK_PUBLISH_HOST}

bootstrap.memory_lock: true

transport:
  publish_port: ${TRANSPORT_PUBLISH_PORT}
  tcp.port: ${TRANSPORT_PORT}


http:
  enabled: ${HTTP_ENABLE}
  port: ${HTTP_PORT}
  publish_port: ${HTTP_PUBLISH_PORT}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

searchguard:
    enterprise_modules_enabled: false
    ssl.transport:
        enabled: true
        pemkey_filepath: ssl/searchguard/cert.key
        pemcert_filepath: ssl/searchguard/cert.pem
        pemtrustedcas_filepath: ssl/searchguard/ca.pem
        enforce_hostname_verification: false
    ssl.http:
        enabled: ${HTTP_SSL}
        clientauth_mode: OPTIONAL
        pemkey_filepath: ssl/searchguard/cert.key
        pemcert_filepath: ssl/searchguard/cert.pem
        pemtrustedcas_filepath: ssl/searchguard/ca.pem

    authcz.admin_dn:
      - "CN=elastic ,OU=devops, C=COM"
